services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sveltekit-app
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
      #  - PORT=3000
      - ORIGIN=https://svelte.vm.lucasdesenv.com
    # networks:
    #   - app-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/"] # Verifica se a página inicial está respondendo
    #   interval: 30s # Intervalo entre as verificações
    #   retries: 3 # Tentativas antes de considerar o container como unhealthy
    #   start_period: 30s # Tempo de espera antes de iniciar as verificações
    #   timeout: 10s # Tempo máximo para a resposta do servidor

  # Optional: Add a database service if needed
  # db:
  #   image: postgres:14-alpine
  #   container_name: sveltekit-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=your_user
  #     - POSTGRES_PASSWORD=your_password
  #     - POSTGRES_DB=your_database
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
# networks:
#   app-network:
#     driver: bridge
# volumes:
#   postgres_data:
